name: Run Feed Script Once A Day

on:
  push:
    branches:
      - main

# on:
#   schedule:
#     - cron: "0 0 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: set up environment variables and execute script
        env:
          RSS_API_KEY: ${{ secrets.RSS_API_KEY }}
        run: |
          npm install
          node scripts/feed-script.js
          echo "Job ran!"
