name: Run Script Periodically

on:
  schedule:
    - cron: "*/2 * * * *" # Runs the job every 2 minutes (adjust as needed)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.1"

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node scripts/script.js

      - name: Give a sign that the job ran
        run: echo "Job ran at $(date)"
